### ISSUE TITLE
THCudaCheck FAIL file: out of memory 

### ISSUE THREAD

**Issue by Jiankai-Sun** [amitshaked/resmatch#5]
Another error occurs. Should I try to run this command again? Or there are other solutions? 
By the way, is there any command option I can use to just jump over the training epoch 11 and continue the testing immediately? 
Thank you!
> jack@gpu02:~/resmatch/src$ th main.lua -ds kitti -a train_mcn -mc resmatch -m hybrid -mc
> net ../storage/net/mc/debug/kitti_resmatch_hybrid_LL_rgb_10_net.t7 -start_epoch 11 -debu
> g -save_img
> ===> Loading matching cost network...
> ===> Loaded! Network: kitti_resmatch_hybrid_LL_rgb
> ===> training matching cost network
>  [======================== 301998/301998 ==============>]  Tot: 6h54m | Step: 81ms
> train epoch 11   err 0.100179   lr 0.003
> 
> ===> testing...
> THCudaCheck FAIL file=/home/jack/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=
> 66 error=2 : out of memory 
> /home/jack/torch/install/bin/luajit: /home/jack/torch/install/share/lua/5.1/nn/Container
> .lua:67:
> In 1 module of nn.ConcatTable:
> In 2 module of nn.Sequential:
> In 9 module of nn.Sequential:
> ./networks/modules/SpatialConvolution1_fw.lua:19: cuda runtime error (2) : out of memory
>  at /home/jack/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
> stack traceback:
>         [C]: in function 'resize'
>         ./networks/modules/SpatialConvolution1_fw.lua:19: in function <./networks/module
> s/SpatialConvolution1_fw.lua:11>
>         [C]: in function 'xpcall'
>         /home/jack/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrow
> Errors'
>         /home/jack/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/jack/torch/install/share/lua/5.1/nn/Sequential.lua:41>
>         [C]: in function 'xpcall'
>         /home/jack/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>         /home/jack/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/jack/torch/install/share/lua/5.1/nn/Sequential.lua:41>
>         [C]: in function 'xpcall'
>         /home/jack/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>         /home/jack/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'forward'
>         ./networks/mc-models/resmatch/hybrid.lua:73: in function 'match'
>         ./runner.lua:29: in function 'predict'
>         ./runner.lua:67: in function 'test'
>         main.lua:87: in main chunk
>         [C]: in function 'dofile'
>         ...jack/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: at 0x00406670 
> 
> WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
> stack traceback:
>         [C]: in function 'error'
>         /home/jack/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
>         /home/jack/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'forward'
>         ./networks/mc-models/resmatch/hybrid.lua:73: in function 'match'
>         ./runner.lua:29: in function 'predict'
>         ./runner.lua:67: in function 'test'
>         main.lua:87: in main chunk
>         [C]: in function 'dofile'
>         ...jack/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: at 0x00406670 

And our GPU Memory is 8G

> +-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:06:00.0     Off |                  N/A |
| 27%   28C    P8     9W / 180W |      0MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by amitshaked** [comment]
The current code requires more memory for training. You can try loading some of the data on every epoch instead all of it at the beginning. 
You can use "-start_epoch" to start at a specific epoch.

**Comment by Jiankai-Sun** [comment]
Thank you! The problem has been solved!

**Comment by Junjiewu2279** [comment]
@Jiankai-Sun I have the same problem.
file:///home/wujunjie/Pictures/Screenshot%20from%202018-07-23%2015-43-32.png
Can you tell me your solution? Thanks
